### ISSUE TITLE
安装好需要的库后，无法启动，见报错

### ISSUE THREAD

**Issue by icesword0760** [1033866383/app_performance#5]
Traceback (most recent call last):
  File "D:\PycharmProjects\app_performance-py_dev\performancetest\web\main.py", line 20, in <module>
    from performancetest.core.task_handle import TaskHandle
  File "D:\PycharmProjects\app_performance-py_dev\performancetest\core\task_handle.py", line 25, in <module>
    class TaskHandle(Process, Actuator):
  File "D:\PycharmProjects\app_performance-py_dev\performancetest\core\task_handle.py", line 27, in TaskHandle
    def __init__(self, serialno: str, server_addr: list[str], package: str, save_dir: str):
TypeError: 'type' object is not subscriptable

**Comment by 1033866383** [comment]
请使用python3.9+因为使用了类型提示
